class bsl_jenkins::config::roles::global::admin {
  augeas { 'config-authorizationStrategy-globalRoles-admin':
    incl    => '/app/jenkins/config.xml',
    lens    => 'Xml.lns',
    changes => [
      # Defining Global Roles
      'defnode globalRolesMap hudson/authorizationStrategy/roleMap[#attribute/type="globalRoles"] ""',

      # Defining the "admin" role
      'defnode adminRole $globalRolesMap/role[#attribute/name="admin"] ""',
      'set $adminRole/#attribute/name admin',
      'set $adminRole/#attribute/pattern .*',
      'set $adminRole/permissions/permission[last()+1]/#text com.cloudbees.plugins.credentials.CredentialsProvider.Create',
      'set $adminRole/permissions/permission[last()+1]/#text com.cloudbees.plugins.credentials.CredentialsProvider.Delete',
      'set $adminRole/permissions/permission[last()+1]/#text com.cloudbees.plugins.credentials.CredentialsProvider.ManageDomains',
      'set $adminRole/permissions/permission[last()+1]/#text com.cloudbees.plugins.credentials.CredentialsProvider.Update',
      'set $adminRole/permissions/permission[last()+1]/#text com.cloudbees.plugins.credentials.CredentialsProvider.UseItem',
      'set $adminRole/permissions/permission[last()+1]/#text com.cloudbees.plugins.credentials.CredentialsProvider.UseOwn',
      'set $adminRole/permissions/permission[last()+1]/#text com.cloudbees.plugins.credentials.CredentialsProvider.View',
      'set $adminRole/permissions/permission[last()+1]/#text com.synopsys.arc.jenkins.plugins.ownership.OwnershipPlugin.Jobs',
      'set $adminRole/permissions/permission[last()+1]/#text com.synopsys.arc.jenkins.plugins.ownership.OwnershipPlugin.Nodes',
      'set $adminRole/permissions/permission[last()+1]/#text hudson.model.Computer.Build',
      'set $adminRole/permissions/permission[last()+1]/#text hudson.model.Computer.Configure',
      'set $adminRole/permissions/permission[last()+1]/#text hudson.model.Computer.Connect',
      'set $adminRole/permissions/permission[last()+1]/#text hudson.model.Computer.Create',
      'set $adminRole/permissions/permission[last()+1]/#text hudson.model.Computer.Delete',
      'set $adminRole/permissions/permission[last()+1]/#text hudson.model.Computer.Disconnect',
      'set $adminRole/permissions/permission[last()+1]/#text hudson.model.Computer.ExtendedRead',
      'set $adminRole/permissions/permission[last()+1]/#text hudson.model.Hudson.Administer',
      'set $adminRole/permissions/permission[last()+1]/#text hudson.model.Hudson.ConfigureUpdateCenter',
      'set $adminRole/permissions/permission[last()+1]/#text hudson.model.Hudson.Read',
      'set $adminRole/permissions/permission[last()+1]/#text hudson.model.Hudson.RunScripts',
      'set $adminRole/permissions/permission[last()+1]/#text hudson.model.Hudson.UploadPlugins',
      'set $adminRole/permissions/permission[last()+1]/#text hudson.model.Item.Build',
      'set $adminRole/permissions/permission[last()+1]/#text hudson.model.Item.Cancel',
      'set $adminRole/permissions/permission[last()+1]/#text hudson.model.Item.Configure',
      'set $adminRole/permissions/permission[last()+1]/#text hudson.model.Item.Create',
      'set $adminRole/permissions/permission[last()+1]/#text hudson.model.Item.Delete',
      'set $adminRole/permissions/permission[last()+1]/#text hudson.model.Item.Discover',
      'set $adminRole/permissions/permission[last()+1]/#text hudson.model.Item.ExtendedRead',
      'set $adminRole/permissions/permission[last()+1]/#text hudson.model.Item.Move',
      'set $adminRole/permissions/permission[last()+1]/#text hudson.model.Item.Read',
      'set $adminRole/permissions/permission[last()+1]/#text hudson.model.Item.WipeOut',
      'set $adminRole/permissions/permission[last()+1]/#text hudson.model.Item.Workspace',
      'set $adminRole/permissions/permission[last()+1]/#text hudson.model.Run.Artifacts',
      'set $adminRole/permissions/permission[last()+1]/#text hudson.model.Run.Delete',
      'set $adminRole/permissions/permission[last()+1]/#text hudson.model.Run.Update',
      'set $adminRole/permissions/permission[last()+1]/#text hudson.model.View.Configure',
      'set $adminRole/permissions/permission[last()+1]/#text hudson.model.View.Create',
      'set $adminRole/permissions/permission[last()+1]/#text hudson.model.View.Delete',
      'set $adminRole/permissions/permission[last()+1]/#text hudson.model.View.Read',
      'set $adminRole/permissions/permission[last()+1]/#text hudson.scm.SCM.Tag',
      'set $adminRole/permissions/permission[last()+1]/#text org.jenkinsci.plugins.envinject.EnvInjectPlugin.ViewVars',
    ],
    notify => Exec['jenkins-config-tidy'],
  }
}
